// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"
	"sync/atomic"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/schema"
	"github.com/99designs/gqlgen/graphql"
	"github.com/dopedao/RYO/api/ent/turn"
	"github.com/hashicorp/go-multierror"
	"golang.org/x/sync/semaphore"
)

// Noder wraps the basic Node method.
type Noder interface {
	Node(context.Context) (*Node, error)
}

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

func (t *Turn) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     t.ID,
		Type:   "Turn",
		Fields: make([]*Field, 32),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(t.UserID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "string",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.LocationID); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "string",
		Name:  "location_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.ItemID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "item_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.BuyOrSell); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "bool",
		Name:  "buy_or_sell",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.AmountToGive); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "schema.BigInt",
		Name:  "amount_to_give",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserCombatStats); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "[]int",
		Name:  "user_combat_stats",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.DrugLordCombatStats); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "[]int",
		Name:  "drug_lord_combat_stats",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.TradeOccurs); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "bool",
		Name:  "trade_occurs",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPreTradeItem); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_pre_trade_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPostTradePreEventItem); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_post_trade_pre_event_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPostTradePostEventItem); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_post_trade_post_event_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPreTradeMoney); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_pre_trade_money",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPostTradePreEventMoney); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_post_trade_pre_event_money",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.UserPostTradePostEventMoney); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "schema.BigInt",
		Name:  "user_post_trade_post_event_money",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPreTradeItem); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_pre_trade_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPostTradePreEventItem); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_post_trade_pre_event_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPostTradePostEventItem); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_post_trade_post_event_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPreTradeMoney); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_pre_tradeMoney",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPostTradePreEventMoney); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_post_trade_pre_eventMoney",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.MarketPostTradePostEventMoney); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "schema.BigInt",
		Name:  "market_post_trade_post_eventMoney",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.DealerDash); err != nil {
		return nil, err
	}
	node.Fields[20] = &Field{
		Type:  "bool",
		Name:  "dealer_dash",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.WrangleDashedDealer); err != nil {
		return nil, err
	}
	node.Fields[21] = &Field{
		Type:  "bool",
		Name:  "wrangle_dashed_dealer",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.Mugging); err != nil {
		return nil, err
	}
	node.Fields[22] = &Field{
		Type:  "bool",
		Name:  "mugging",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.RunFromMugging); err != nil {
		return nil, err
	}
	node.Fields[23] = &Field{
		Type:  "bool",
		Name:  "run_from_mugging",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.GangWar); err != nil {
		return nil, err
	}
	node.Fields[24] = &Field{
		Type:  "bool",
		Name:  "gang_war",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.DefendGangWar); err != nil {
		return nil, err
	}
	node.Fields[25] = &Field{
		Type:  "bool",
		Name:  "defend_gang_war",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.CopRaid); err != nil {
		return nil, err
	}
	node.Fields[26] = &Field{
		Type:  "bool",
		Name:  "cop_raid",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.BribeCops); err != nil {
		return nil, err
	}
	node.Fields[27] = &Field{
		Type:  "bool",
		Name:  "bribe_cops",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.FindItem); err != nil {
		return nil, err
	}
	node.Fields[28] = &Field{
		Type:  "bool",
		Name:  "find_item",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.LocalShipment); err != nil {
		return nil, err
	}
	node.Fields[29] = &Field{
		Type:  "bool",
		Name:  "local_shipment",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.WarehouseSeizure); err != nil {
		return nil, err
	}
	node.Fields[30] = &Field{
		Type:  "bool",
		Name:  "warehouse_seizure",
		Value: string(buf),
	}
	if buf, err = json.Marshal(t.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[31] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	return node, nil
}

func (c *Client) Node(ctx context.Context, id int) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}

var errNodeInvalidID = &NotFoundError{"node"}

// NodeOption allows configuring the Noder execution using functional options.
type NodeOption func(*nodeOptions)

// WithNodeType sets the node Type resolver function (i.e. the table to query).
// If was not provided, the table will be derived from the universal-id
// configuration as described in: https://entgo.io/docs/migrate/#universal-ids.
func WithNodeType(f func(context.Context, int) (string, error)) NodeOption {
	return func(o *nodeOptions) {
		o.nodeType = f
	}
}

// WithFixedNodeType sets the Type of the node to a fixed value.
func WithFixedNodeType(t string) NodeOption {
	return WithNodeType(func(context.Context, int) (string, error) {
		return t, nil
	})
}

type nodeOptions struct {
	nodeType func(context.Context, int) (string, error)
}

func (c *Client) newNodeOpts(opts []NodeOption) *nodeOptions {
	nopts := &nodeOptions{}
	for _, opt := range opts {
		opt(nopts)
	}
	if nopts.nodeType == nil {
		nopts.nodeType = func(ctx context.Context, id int) (string, error) {
			return c.tables.nodeType(ctx, c.driver, id)
		}
	}
	return nopts
}

// Noder returns a Node by its id. If the NodeType was not provided, it will
// be derived from the id value according to the universal-id configuration.
//
//		c.Noder(ctx, id)
//		c.Noder(ctx, id, ent.WithNodeType(pet.Table))
//
func (c *Client) Noder(ctx context.Context, id int, opts ...NodeOption) (_ Noder, err error) {
	defer func() {
		if IsNotFound(err) {
			err = multierror.Append(err, entgql.ErrNodeNotFound(id))
		}
	}()
	table, err := c.newNodeOpts(opts).nodeType(ctx, id)
	if err != nil {
		return nil, err
	}
	return c.noder(ctx, table, id)
}

func (c *Client) noder(ctx context.Context, table string, id int) (Noder, error) {
	switch table {
	case turn.Table:
		n, err := c.Turn.Query().
			Where(turn.ID(id)).
			CollectFields(ctx, "Turn").
			Only(ctx)
		if err != nil {
			return nil, err
		}
		return n, nil
	default:
		return nil, fmt.Errorf("cannot resolve noder from table %q: %w", table, errNodeInvalidID)
	}
}

func (c *Client) Noders(ctx context.Context, ids []int, opts ...NodeOption) ([]Noder, error) {
	switch len(ids) {
	case 1:
		noder, err := c.Noder(ctx, ids[0], opts...)
		if err != nil {
			return nil, err
		}
		return []Noder{noder}, nil
	case 0:
		return []Noder{}, nil
	}

	noders := make([]Noder, len(ids))
	errors := make([]error, len(ids))
	tables := make(map[string][]int)
	id2idx := make(map[int][]int, len(ids))
	nopts := c.newNodeOpts(opts)
	for i, id := range ids {
		table, err := nopts.nodeType(ctx, id)
		if err != nil {
			errors[i] = err
			continue
		}
		tables[table] = append(tables[table], id)
		id2idx[id] = append(id2idx[id], i)
	}

	for table, ids := range tables {
		nodes, err := c.noders(ctx, table, ids)
		if err != nil {
			for _, id := range ids {
				for _, idx := range id2idx[id] {
					errors[idx] = err
				}
			}
		} else {
			for i, id := range ids {
				for _, idx := range id2idx[id] {
					noders[idx] = nodes[i]
				}
			}
		}
	}

	for i, id := range ids {
		if errors[i] == nil {
			if noders[i] != nil {
				continue
			}
			errors[i] = entgql.ErrNodeNotFound(id)
		} else if IsNotFound(errors[i]) {
			errors[i] = multierror.Append(errors[i], entgql.ErrNodeNotFound(id))
		}
		ctx := graphql.WithPathContext(ctx,
			graphql.NewPathWithIndex(i),
		)
		graphql.AddError(ctx, errors[i])
	}
	return noders, nil
}

func (c *Client) noders(ctx context.Context, table string, ids []int) ([]Noder, error) {
	noders := make([]Noder, len(ids))
	idmap := make(map[int][]*Noder, len(ids))
	for i, id := range ids {
		idmap[id] = append(idmap[id], &noders[i])
	}
	switch table {
	case turn.Table:
		nodes, err := c.Turn.Query().
			Where(turn.IDIn(ids...)).
			CollectFields(ctx, "Turn").
			All(ctx)
		if err != nil {
			return nil, err
		}
		for _, node := range nodes {
			for _, noder := range idmap[node.ID] {
				*noder = node
			}
		}
	default:
		return nil, fmt.Errorf("cannot resolve noders from table %q: %w", table, errNodeInvalidID)
	}
	return noders, nil
}

type tables struct {
	once  sync.Once
	sem   *semaphore.Weighted
	value atomic.Value
}

func (t *tables) nodeType(ctx context.Context, drv dialect.Driver, id int) (string, error) {
	tables, err := t.Load(ctx, drv)
	if err != nil {
		return "", err
	}
	idx := int(id / (1<<32 - 1))
	if idx < 0 || idx >= len(tables) {
		return "", fmt.Errorf("cannot resolve table from id %v: %w", id, errNodeInvalidID)
	}
	return tables[idx], nil
}

func (t *tables) Load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	t.once.Do(func() { t.sem = semaphore.NewWeighted(1) })
	if err := t.sem.Acquire(ctx, 1); err != nil {
		return nil, err
	}
	defer t.sem.Release(1)
	if tables := t.value.Load(); tables != nil {
		return tables.([]string), nil
	}
	tables, err := t.load(ctx, drv)
	if err == nil {
		t.value.Store(tables)
	}
	return tables, err
}

func (*tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
		From(sql.Table(schema.TypeTable)).
		OrderBy(sql.Asc("id")).
		Query()
	if err := drv.Query(ctx, query, args, rows); err != nil {
		return nil, err
	}
	defer rows.Close()
	var tables []string
	return tables, sql.ScanSlice(rows, &tables)
}
