// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dopedao/RYO/api/ent/schema"
	"github.com/dopedao/RYO/api/ent/turn"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	turnFields := schema.Turn{}.Fields()
	_ = turnFields
	// turnDescUserID is the schema descriptor for user_id field.
	turnDescUserID := turnFields[0].Descriptor()
	// turn.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	turn.UserIDValidator = turnDescUserID.Validators[0].(func(string) error)
	// turnDescLocationID is the schema descriptor for location_id field.
	turnDescLocationID := turnFields[1].Descriptor()
	// turn.LocationIDValidator is a validator for the "location_id" field. It is called by the builders before save.
	turn.LocationIDValidator = turnDescLocationID.Validators[0].(func(string) error)
	// turnDescItemID is the schema descriptor for item_id field.
	turnDescItemID := turnFields[2].Descriptor()
	// turn.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	turn.ItemIDValidator = turnDescItemID.Validators[0].(func(string) error)
	// turnDescCreatedAt is the schema descriptor for created_at field.
	turnDescCreatedAt := turnFields[31].Descriptor()
	// turn.DefaultCreatedAt holds the default value on creation for the created_at field.
	turn.DefaultCreatedAt = turnDescCreatedAt.Default.(func() time.Time)
}
